[project]
name = "litellm-pass-through-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "backoff>=2.2.1",
    "httpx>=0.28.1",
    "litellm[proxy]>=1.80.7",
    "pytest>=9.0.1",
    "pytest-asyncio>=1.3.0",
]
